#!/bin/sh

if ( [ "$1" == "-d" ] ); then
    DEBUGGER="-debugger :51000"
    shift
else
    DEBUGGER=""
fi

if ( [ "$1" == "compile" ] ); then
    cache/release/jazz -compile world.stream.foreign
    exit
fi

SCRIPT="$1"
shift

cache/release/jazz $DEBUGGER -run stream -script $SCRIPT "$@"
